// src/app/layout.tsx
import './globals.css';

export const metadata = {
  // Using the metadata from your uploaded file, or update as needed
  title: 'Create Next App', // Or 'Argus' as you might prefer
  description: 'Generated by create next app', // Or your custom description
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* Temporarily remove inter.className from here */}
      <body>
        {children}
      </body>
    </html>
  );
}