/** To summarize, this code imports a CSS file for styling, exports an object containing metadata about the web application, and exports a React component called "RootLayout" that provides a basic structure for rendering content within the body of a web page. */

import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
